version: "3.8"
services:
  cost-service:
    labels:
      app: graphql-grpc
    build:
      labels:
        app: graphql-grpc
      context: ./cost-service
    image: amitsingh00/cost-service

  document-service:
    labels:
      app: graphql-grpc
    build:
      labels:
        app: graphql-grpc
      context: ./document-service
    image: amitsingh00/document-service

  api-graphql:
    labels:
      app: graphql-grpc
    build:
      labels:
        app: graphql-grpc
      context: ./api-graphql
    image: amitsingh00/api-graphql
    ports:
      - "8080:8080"
