// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cost.proto

package com.example.grpc.cost;

public final class Cost {
  private Cost() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_cost_PlanCostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_cost_PlanCostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_cost_PlanCostResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_cost_PlanCostResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_cost_PlanCost_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_cost_PlanCost_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncost.proto\022\025com.example.grpc.cost\"#\n\017P" +
      "lanCostRequest\022\020\n\010planCode\030\001 \003(\t\"A\n\020Plan" +
      "CostResponse\022-\n\004cost\030\001 \003(\0132\037.com.example" +
      ".grpc.cost.PlanCost\"K\n\010PlanCost\022\020\n\010planC" +
      "ode\030\001 \001(\t\022\025\n\remplCovrgRate\030\002 \001(\002\022\026\n\016empl" +
      "rCovrgRate\030\003 \001(\002B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_cost_PlanCostRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_cost_PlanCostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_cost_PlanCostRequest_descriptor,
        new java.lang.String[] { "PlanCode", });
    internal_static_com_example_grpc_cost_PlanCostResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_cost_PlanCostResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_cost_PlanCostResponse_descriptor,
        new java.lang.String[] { "Cost", });
    internal_static_com_example_grpc_cost_PlanCost_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_cost_PlanCost_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_cost_PlanCost_descriptor,
        new java.lang.String[] { "PlanCode", "EmplCovrgRate", "EmplrCovrgRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
