// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cost.proto

package com.example.grpc.cost;

public interface PlanCostRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.cost.PlanCostRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string planCode = 1;</code>
   * @return A list containing the planCode.
   */
  java.util.List<java.lang.String>
      getPlanCodeList();
  /**
   * <code>repeated string planCode = 1;</code>
   * @return The count of planCode.
   */
  int getPlanCodeCount();
  /**
   * <code>repeated string planCode = 1;</code>
   * @param index The index of the element to return.
   * @return The planCode at the given index.
   */
  java.lang.String getPlanCode(int index);
  /**
   * <code>repeated string planCode = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the planCode at the given index.
   */
  com.google.protobuf.ByteString
      getPlanCodeBytes(int index);
}
