// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cost.proto

package com.example.grpc.cost;

public interface PlanCostResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.cost.PlanCostResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.grpc.cost.PlanCost cost = 1;</code>
   */
  java.util.List<com.example.grpc.cost.PlanCost> 
      getCostList();
  /**
   * <code>repeated .com.example.grpc.cost.PlanCost cost = 1;</code>
   */
  com.example.grpc.cost.PlanCost getCost(int index);
  /**
   * <code>repeated .com.example.grpc.cost.PlanCost cost = 1;</code>
   */
  int getCostCount();
  /**
   * <code>repeated .com.example.grpc.cost.PlanCost cost = 1;</code>
   */
  java.util.List<? extends com.example.grpc.cost.PlanCostOrBuilder> 
      getCostOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.cost.PlanCost cost = 1;</code>
   */
  com.example.grpc.cost.PlanCostOrBuilder getCostOrBuilder(
      int index);
}
