// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cost.proto

package com.example.grpc.cost;

public interface PlanCostOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.cost.PlanCost)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string planCode = 1;</code>
   * @return The planCode.
   */
  java.lang.String getPlanCode();
  /**
   * <code>string planCode = 1;</code>
   * @return The bytes for planCode.
   */
  com.google.protobuf.ByteString
      getPlanCodeBytes();

  /**
   * <code>float emplCovrgRate = 2;</code>
   * @return The emplCovrgRate.
   */
  float getEmplCovrgRate();

  /**
   * <code>float emplrCovrgRate = 3;</code>
   * @return The emplrCovrgRate.
   */
  float getEmplrCovrgRate();
}
